apiVersion: v1
kind: Service
metadata:
  name: task-metrics-api-app
  namespace: default
  labels:
    app.kubernetes.io/name: task-metrics-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: task-metrics-api